# Generated by Django 3.0.2 on 2020-02-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20200213_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='exercise',
            field=models.ManyToManyField(blank=True, related_name='workout_mm', to='diary.Exercise'),
        ),
    ]
