# Generated by Django 3.0.2 on 2020-04-17 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20200417_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='id',
            new_name='exercise_id',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='id',
            new_name='workout_id',
        ),
    ]
