# Generated by Django 3.0.2 on 2020-02-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20200213_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='workout',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sets',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='diary.Set'),
        ),
    ]
