# Generated by Django 3.0.2 on 2020-02-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20200213_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='sets',
            field=models.ManyToManyField(blank=True, related_name='exercises_mm', to='diary.Set'),
        ),
    ]
