# Generated by Django 3.0.2 on 2020-03-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20200312_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='workout',
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout',
            field=models.ManyToManyField(blank=True, related_name='exercise_mm', to='diary.Workout'),
        ),
    ]
