# Generated by Django 3.0.2 on 2020-02-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_auto_20200213_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='exercise',
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout',
            field=models.ManyToManyField(blank=True, related_name='exercise_mm', to='diary.Workout'),
        ),
    ]
