# Generated by Django 3.0.2 on 2020-02-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_remove_exercise_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='exercise',
            field=models.ManyToManyField(blank=True, related_name='set_mm', to='diary.Exercise'),
        ),
    ]
