# Generated by Django 3.0.3 on 2020-02-21 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_auto_20200214_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={},
        ),
        migrations.AddField(
            model_name='set',
            name='user_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
