# Generated by Django 3.0.3 on 2020-02-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_auto_20200221_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='user_date',
        ),
    ]
