# Generated by Django 3.0.3 on 2020-03-20 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_auto_20200320_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='exercise',
        ),
        migrations.AddField(
            model_name='set',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_mm', to='diary.Exercise'),
        ),
    ]
