# Generated by Django 3.0.2 on 2020-03-22 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0012_auto_20200322_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='reps',
            field=models.PositiveIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_number',
            field=models.PositiveIntegerField(default='', max_length=2, validators=[django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='set',
            name='weight',
            field=models.PositiveIntegerField(default=''),
        ),
    ]
