# Generated by Django 3.0.2 on 2020-03-22 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0013_auto_20200322_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='set_number',
            field=models.PositiveIntegerField(default='', validators=[django.core.validators.MaxValueValidator(2)]),
        ),
    ]
