# Generated by Django 3.0.3 on 2020-04-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0016_auto_20200404_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='weight',
            field=models.PositiveIntegerField(blank=True, default='', null=True),
        ),
    ]
